# Generated by Django 4.1.7 on 2023-08-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
