# Generated by Django 4.1.7 on 2023-08-01 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0002_staff_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('recommended_level', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplus_app.staff')),
            ],
        ),
    ]
