# Generated by Django 4.1.7 on 2023-08-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
