# Generated by Django 4.1.7 on 2023-08-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0004_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplus_app.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplus_app.group')),
            ],
        ),
    ]
