# Generated by Django 4.1.7 on 2023-08-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0005_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('index_number', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('group', models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='aplus_app.group')),
            ],
        ),
    ]
