# Generated by Django 4.1.7 on 2023-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0007_remove_student_index_number_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registered_students',
            field=models.JSONField(default={'data': []}),
        ),
    ]
