# Generated by Django 4.1.7 on 2023-08-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0008_course_registered_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='registered_students',
        ),
    ]
