# Generated by Django 4.1.7 on 2023-08-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0010_course_registered_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='attendants',
            field=models.JSONField(default={'data': []}),
        ),
    ]
