# Generated by Django 4.1.7 on 2023-08-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0011_room_attendants'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='key',
            field=models.TextField(default='123456'),
        ),
    ]
