# Generated by Django 4.1.7 on 2023-08-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0012_room_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateField(default='2023-05-08'),
        ),
    ]
