# Generated by Django 4.1.7 on 2023-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0013_room_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
