# Generated by Django 4.1.7 on 2023-08-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplus_app', '0015_room_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='qrcode',
            field=models.ImageField(blank=True, default='qrcodes/default', null=True, upload_to='qrcodes'),
        ),
    ]
